2023-06-03 11:52:37,020 ERROR: Exception on /index [GET] [in C:\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\main\routes.py", line 22, in index
    return render_template('index.html', title=_('Home'), posts=posts)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2023-06-03 11:52:37,994 ERROR: Exception on /index [GET] [in C:\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\main\routes.py", line 22, in index
    return render_template('index.html', title=_('Home'), posts=posts)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2023-06-03 11:53:05,500 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-03 11:55:21,953 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-03 11:55:30,658 ERROR: Exception on / [GET] [in C:\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\main\routes.py", line 22, in index
    return render_template('index.html', title=_('Home'), posts=posts)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\templates\index.html", line 34, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endwith'. The innermost block that needs to be closed is 'with'.
2023-06-03 11:57:19,728 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 04:57:53,728 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 04:58:52,759 ERROR: Exception on / [GET] [in C:\Python310\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\main\routes.py", line 22, in index
    return render_template('index.html', title=_('Home'), posts=posts)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\templates\index.html", line 14, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2023-06-05 05:01:20,460 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:14:41,694 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:24:47,054 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:25:57,885 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:32:20,986 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:33:06,790 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:34:52,392 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
2023-06-05 05:36:19,097 INFO: Microblog startup [in C:\Users\Administrator\Documents\Wellfound-Assessment\microblog\app\__init__.py:95]
